### ISSUE TITLE
Add Validation

### ISSUE THREAD

**Issue by MarySed** [Robb-S/plainlist#2]
This is really impressive!! And the names are so cute!! 

One of the things I noticed is there is no validation on the `AddItem.js`

If you make the name or note too long (I'm too lazy to see how long exactly), it causes the database op to fail. 
Maybe you can have a local state of hasError (or something) that is set to true if either fields are too long, and disables the submit button for a better user experience 

<img width="461" alt="Screenshot 2021-08-06 012942" src="https://user-images.githubusercontent.com/37863665/128386764-18531558-1452-4de3-8910-0ad973d7e8aa.png">

**Comment by Robb-S** [comment]
Submission buttons are now disabled if trimmed text fields are too long or too short (e.g. blank).
